### ISSUE TITLE
API Call

### ISSUE THREAD

**Issue by drlovelove** [t894924815/BusTool#1]
which API are you using to call ?

**Comment by fouriertry** [comment]
@drlovelove GaoDe map API

**Comment by drlovelove** [comment]
So, you are saying GaoDe Map API shows Chelaile BusLine ? or you're using both ?

**Comment by fouriertry** [comment]
@drlovelove  only  GaoDe Map API, it's convenient for this app.

**Comment by drlovelove** [comment]
If so then where did you pool bus line data and arrival time from ? As far i know GaoDe ( Amap) is just a map not a transit operator. Is your app available in any app store ? I would like to try.

**Comment by fouriertry** [comment]
@drlovelove my bus line data is from → http://lbs.amap.com/getting-started/path

**Comment by drlovelove** [comment]
Can you see the bus line arrival time from this link ? I'm trying to filter specific bus lines for Chongqing. I wanna show the arrival time.
